version: '3.7'
services:
  db:
    image: timescale/timescaledb:latest-pg12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TS_TUNE_CPUS: 2
      TS_TUNE_MEMORY: '1GB'

  gradcafe:
    command: [ 'echo', '==> Image gradcafe:latest built locally.' ]
    build:
      context: .
      dockerfile: Dockerfile
    image: gradcafe:latest

  scrape:
    command: [ 'bash', '-c', 'python scrape.py --seeds $SEEDS']
    image: gradcafe:latest
    env_file: .env
    depends_on:
      - db
      - gradcafe
